base_url = "https://creekmore.dev"

title = "Morgan Creekmore"
author = "Morgan Creekmore"
description = "Software Engineer and 3D Artist"

compile_sass = true
build_search_index = false

[markdown]
highlight_code = false

[extra]
# https://www.goatcounter.com/
goatcounter = "grbt-personal"