base_url = "https://morgancreekmore.me"

title = "Morgan Creekmore"
author = "Morgan Creekmore"
description = "Doing Stuff"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
# https://www.goatcounter.com/
goatcounter = "grbt-personal"