base_url = "https://creekmore.dev"

title = "Morgan Creekmore"
author = "Morgan Creekmore"
description = "Software Engineer doing C#/.NET, C/C++, and Rust"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
# https://www.goatcounter.com/
goatcounter = "grbt-personal"